### ISSUE TITLE
[Bug] onNext/onPrevious not called on swipe

### ISSUE THREAD

**Issue by connor-baer** [infiniteluke/dub-step#4]
Hi! Thanks for creating this really useful component! 👏 

I'm currently building a carousel and I'd like to run the same CSS animations when swiping and when clicking the next/previous buttons. For this I need to know the direction: should I animate to the next slide or the previous one? I've got it to work with the `onPrevious` and `onNext` props, but only when clicking the buttons. Looking at the source code, it seems that these methods are not called on swipe. Is this a bug or intentional?

I think it would be useful to call these functions when the index changes, no matter how the change was initiated. Alternatively it would be useful to expose the `previousIndex`/`nextIndex` so I could determine the direction myself. 

I'd be happy to submit a PR 🙂

**Comment by connor-baer** [comment]
Update: I got it to work with the `onBeforeChange` method. 

However, I still think that `onPrevious` and `onNext` should be called on swipe as well, for consistency.

**Comment by infiniteluke** [comment]
Thanks!

Check out the `SimpleCarousel` in the codesandbox for one way to handling swiping animations: https://codesandbox.io/s/p5vr4pq897

**Comment by connor-baer** [comment]
Thanks, my use case is a bit more complicated though 😉 

What about calling `onPrevious` and `onNext` on swipe as well, for consistency? Can I create a PR or do you wanna keep it the way it is?

**Comment by infiniteluke** [comment]
PR's are always welcome! I'm not sure I understand how what you're asking for is different than the example on codesandbox, though. See the GIF/code/explanation below.

![simplecarouselswipeanimation](https://user-images.githubusercontent.com/1127238/30926436-0126445c-a36a-11e7-85d9-35bab4330932.gif)

```jsx

const DogeImg = glamorous.img(props => ({
  boxSizing: 'border-box',
  width: '100%',
  height: '100%',
  transform: `translate3d(${props.swipeLeftDistance}px, 0, 0) scale(${props.i ===
  props.index
    ? 1.05
    : 1})`,
  transition: !props.dragging ? 'all .3s ease-in-out' : undefined,
  padding: '20px'
}));

const SimpleCarouselWrapper = glamorous.div({
  margin: '0 auto',
  overflow: 'hidden',
  width: '350px'
});

const SimpleCarouselSlides = glamorous.section(props => ({
  display: 'flex',
  transform: `translate3d(${-props.index * 350}px, 0, 0)`,
  transition: 'all .3s ease-in-out'
}));
```

When I click and drag the image, the transform in `DogeImg` is getting the `swipeLeftDistance` and moving the slide respectively. When I let go of the mouse, internally, dub-step is calculating if the swipe threshold was crossed. If it was, the `index` is updated appropriately. When the `index` updates, `SimpleCarouselSlides` transitions the slide the "rest" of the way, the same way that it would if the next/prev button was clicked. 

If this isn't what you're trying to accomplish, let me know. I would love to help you solve it and update dub-step to help if needed.

**Comment by infiniteluke** [comment]
That said, the original bug you filed is correct. In `swipeEnd`, by calling `changeSlide` directly instead of using `next` and `previous`, the callback will not be called. This was originally intentional because I was going to add the ability to swipe across multiple slides. That isn't implemented yet so we should fix this until then.

Here's the offending code. PRs are welcome! I probably won't have time to get this up until later this week.
https://github.com/infiniteluke/dub-step/blob/master/src/dub-step.js#L565-L580
