### ISSUE TITLE
setState() can only update a mounted or mounting component warnings

### ISSUE THREAD

**Issue by lkbr** [infiniteluke/dub-step#9]
Thank you for this component. Love the name and approach. 

I'm getting `Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the DubStep component.` 

It happens when I have a `<DubStep />` with `autoplay` and `duration` set and then navigate to another page in a Next.js app.

I can produce a minimal example if its not immediately obvious what the cause is.

**Comment by infiniteluke** [comment]
Hi @lkbr - Thanks for noting this issue. Can you please provide some example code for how you're using dub-step?

**Comment by lkbr** [comment]
Here is a [codesandbox](https://codesandbox.io/s/y3zork27r1) with react router. I added dub-steps `<BasicSlideshow />` example with `autoPlay` to `components/Home.js` in the sandbox.

You can see the setState warning in the console when you navigate away from the `/` route by clicking About or Topics.

**Comment by infiniteluke** [comment]
@lkbr - This should be fixed with https://github.com/infiniteluke/dub-step/commit/92bf89046674892395b275a9569d255678ba9543. `componentWillUnmount` must have gotten wiped during a refactor 🙃 .

You should be able to bump the version of dub-step in your codesandbox and see this fixed now.

Thanks!

**Comment by lkbr** [comment]
It is! Thank you.
